### ISSUE TITLE
Some error is thrown

### ISSUE THREAD

**Issue by hareendras** [ruial/9gag#7]
SyntaxError: Unexpected token O in JSON at position 0
     at JSON.parse (<anonymous>)
     at HttpClient.get (/app/node_modules/9gag/src/httpclient.js:20:17)
     at <anonymous>
     at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by ruial** [comment]
Cloudflare is blocking more requests again. By chance, when messing with the node-fetch library, I found out that having the string "https://" somewhere in the user agent allows requests to go through, e.g.:

`curl 'https://9gag.com/v1/group-posts/group/default/type/hot' -H 'user-agent: https://'`

My guess is they have a bad firewall rule, which will get fixed eventually. I changed the package to allow custom HTTP Clients, as long as they have the same interface (a *get* method to return the json response). If I can't update the package, users can try different ways to get it working. The default HTTP client uses node-fetch currently.

You can upgrade the package to version 4 :)

Is it working on your side?

**Comment by hareendras** [comment]
Hi,
Thank you for your input. But once I've updated it to version 4.0.0 it throws below error
```
 TypeError: httpClient.init is not a function
    at /app/index.js:72:32
    at <anonymous>
```
I was using below code before...
```
const HttpClient = NineGag.HttpClient;
const httpClient = new HttpClient();
await httpClient.init();
const scraper = new Scraper(httpClient, 10, category[i], 0);
```


I tried passing the HttpClient  without calling init() method. In this case, no posts are returned.
```
const HttpClient = NineGag.HttpClient;
const httpClient = new HttpClient();
//await httpClient.init();
const scraper = new Scraper(httpClient, 10, category[i], 0);
```
Can I have a sample code to make this work please?

**Comment by ruial** [comment]
I changed the API a bit, hence the major version update. If you check the README, you notice that the httpClient stuff can be removed, or passed as the last argument

**Comment by hareendras** [comment]
Hi. My apologies for not referring Readme. I removed HttpClient. Now it works!! Thanks a lot
